"""Formatadores de comentário GitHub a partir de findings de pentest."""

from __future__ import annotations

from enum import Enum
from typing import Any


class CommentStyle(Enum):
    DETAILED = "detailed"
    SUMMARY = "summary"
    MINIMAL = "minimal"
    REMEDIATION = "remediation"


def group_by_severity(findings: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {
        "critical": [],
        "high": [],
        "medium": [],
        "low": [],
        "info": [],
        "unknown": [],
    }
    for finding in findings:
        severity = str(finding.get("severity") or "unknown").lower()
        if severity not in grouped:
            severity = "unknown"
        grouped[severity].append(finding)
    return grouped


def format_finding_block(finding: dict[str, Any]) -> list[str]:
    title = str(finding.get("title") or "Unknown issue")
    remediation = str(
        finding.get("remediation")
        or finding.get("remediation_title")
        or "See report for remediation"
    )
    host = str(finding.get("host") or finding.get("url") or finding.get("matched_at") or "")
    evidence = str(finding.get("evidence") or "")[:300]
    block = [f"- **{title}**"]
    if host:
        block.append(f"  - Location: `{host}`")
    if evidence:
        block.append(f"  - Evidence: {evidence}")
    block.append(f"  - Fix: {remediation}")
    block.append("")
    return block


class GitHubCommentFormatter:
    @staticmethod
    def format(
        findings: list[dict[str, Any]],
        style: CommentStyle = CommentStyle.SUMMARY,
        *,
        title: str = "DarkStar Security Review",
        target: str = "",
        risk_profile: str = "",
    ) -> str:
        if style == CommentStyle.DETAILED:
            return GitHubCommentFormatter._format_detailed(
                findings, title=title, target=target, risk_profile=risk_profile
            )
        if style == CommentStyle.MINIMAL:
            return GitHubCommentFormatter._format_minimal(findings, title=title)
        if style == CommentStyle.REMEDIATION:
            return GitHubCommentFormatter._format_remediation(findings, title=title)
        return GitHubCommentFormatter._format_summary(
            findings, title=title, target=target, risk_profile=risk_profile
        )

    @staticmethod
    def _format_summary(
        findings: list[dict[str, Any]],
        *,
        title: str,
        target: str,
        risk_profile: str,
    ) -> str:
        grouped = group_by_severity(findings)
        lines = [
            f"## {title}",
            "",
            "### Summary",
            f"- **Total issues:** {len(findings)}",
        ]
        if target:
            lines.append(f"- **Target:** `{target}`")
        if risk_profile:
            lines.append(f"- **Risk profile:** {risk_profile}")
        lines.extend(
            [
                f"- **Critical:** {len(grouped['critical'])}",
                f"- **High:** {len(grouped['high'])}",
                f"- **Medium:** {len(grouped['medium'])}",
                f"- **Low:** {len(grouped['low'])}",
                "",
            ]
        )
        if grouped["critical"]:
            lines.append("### Critical")
            lines.append("")
            for f in grouped["critical"][:5]:
                lines.extend(format_finding_block(f))
        if grouped["high"]:
            lines.append("### High")
            lines.append("")
            for f in grouped["high"][:3]:
                lines.extend(format_finding_block(f))
        lines.extend(
            [
                "---",
                "*Generated by DarkStar — authorized targets only.*",
            ]
        )
        return "\n".join(lines)

    @staticmethod
    def _format_detailed(
        findings: list[dict[str, Any]],
        *,
        title: str,
        target: str,
        risk_profile: str,
    ) -> str:
        base = GitHubCommentFormatter._format_summary(
            findings, title=title, target=target, risk_profile=risk_profile
        )
        extra = ["", "### All findings", ""]
        for f in findings[:40]:
            extra.extend(format_finding_block(f))
        return base + "\n".join(extra)

    @staticmethod
    def _format_minimal(findings: list[dict[str, Any]], *, title: str) -> str:
        lines = [f"## {title}", ""]
        for f in findings:
            sev = str(f.get("severity") or "?").upper()
            lines.append(f"- [{sev}] {f.get('title') or 'Unknown'}")
        return "\n".join(lines)

    @staticmethod
    def _format_remediation(findings: list[dict[str, Any]], *, title: str) -> str:
        lines = [f"## {title} — remediation", ""]
        for f in findings:
            rem = f.get("remediation") or f.get("remediation_title") or "N/A"
            lines.append(f"### {f.get('title') or 'Issue'}")
            lines.append(str(rem))
            lines.append("")
        return "\n".join(lines)
